### ISSUE TITLE
CEF Connectivity Unknown error

### ISSUE THREAD

**Issue by Kim-Billit** [OxalisCommunity/Oxalis-AS4#119]
I am trying to perform the CEF Connectivity test but I am having some issues.

Error:
`2020-04-16 15:45:03,770 ERROR [eu.sendregning.oxalis.Main] [] Execution failed: no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: Failed to send message 
java.util.concurrent.ExecutionException: no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: Failed to send message
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at eu.sendregning.oxalis.Main.main(Main.java:227)
Caused by: no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: Failed to send message
	at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:108)
	at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:89)
	at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
	at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
	at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.xml.ws.soap.SOAPFaultException: An error occurred while processing your request. Please check the message header for more details.
	at org.apache.cxf.jaxws.DispatchImpl.mapException(DispatchImpl.java:285)
	at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:330)
	at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
	at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:105)
	... 14 common frames omitted
Caused by: org.apache.cxf.binding.soap.SoapFault: An error occurred while processing your request. Please check the message header for more details.
	at org.apache.cxf.binding.soap.interceptor.Soap12FaultInInterceptor.unmarshalFault(Soap12FaultInInterceptor.java:156)
	at org.apache.cxf.binding.soap.interceptor.Soap12FaultInInterceptor.handleMessage(Soap12FaultInInterceptor.java:66)
	at org.apache.cxf.binding.soap.interceptor.Soap12FaultInInterceptor.handleMessage(Soap12FaultInInterceptor.java:52)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:112)
	at org.apache.cxf.binding.soap.interceptor.CheckFaultInterceptor.handleMessage(CheckFaultInterceptor.java:70)
	at org.apache.cxf.binding.soap.interceptor.CheckFaultInterceptor.handleMessage(CheckFaultInterceptor.java:35)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:829)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1693)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1570)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1371)
	at org.apache.cxf.ext.logging.LoggingOutputStream.postClose(LoggingOutputStream.java:53)
	at org.apache.cxf.io.CachedOutputStream.close(CachedOutputStream.java:228)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:671)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
	at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
	at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)
	... 16 common frames omitted`

When looking in the message header this is what it shows:

`<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope">
    <env:Header>
        <eb:Messaging xmlns:eb="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/" env:mustUnderstand="true">
            <eb:SignalMessage>
                <eb:MessageInfo>
                    <eb:Timestamp>2020-04-16T13:45:03.527Z</eb:Timestamp>
                    <eb:MessageId>44484980-d72f-4bae-91bd-fd469aaf3e1f@domibus.eu</eb:MessageId>
                </eb:MessageInfo>
                <eb:Error category="CONTENT" errorCode="EBMS:0004" origin="ebMS" severity="failure" shortDescription="Other">
                    <eb:Description xml:lang="">Other</eb:Description>
                    <eb:ErrorDetail>unknown error occurred</eb:ErrorDetail>
                </eb:Error>
            </eb:SignalMessage>
        </eb:Messaging>
    </env:Header>
    <env:Body>
        <env:Fault>
            <env:Code>
                <env:Value>env:Receiver</env:Value>
            </env:Code>
            <env:Reason>
                <env:Text xml:lang="en">An error occurred while processing your request. Please check the message header for more details.</env:Text>
            </env:Reason>
        </env:Fault>
    </env:Body>
</env:Envelope>`

"Unknown error occured" doens't really help me to see where the error is taking place.

My oxalis.conf looks like this:

```
oxalis.keystore {
     # Relative to OXALIS_HOME
     path=ceftestparty105gwkeystore.jks
     password = ***
     key.alias = ceftestparty105gw
     key.password = ***
 }

security.truststore.ap=ceftestparty105gwtruststore.jks
security.truststore.password=***

oxalis.as4.type=cef-connectivity

lookup.locator.hostname="acc.edelivery.tech.ec.europa.eu/edelivery-sml/"
lookup.locator.class = no.difi.vefa.peppol.lookup.locator.BusdoxLocator

security.validator.class = no.difi.vefa.peppol.security.util.EmptyCertificateValidator

oxalis.path.inbound = "c:/OXALIS_HOME/inbound"

oxalis.logging.config=logback.xml
```

And the command I am using is the folowing:

`java -DOXALIS_HOME=C:/OXALIS_HOME^
   -classpath "standalone/*;as4/*"^
   eu.sendregning.oxalis.Main^
   -cert cefsupportgw.cer^
   -f payload_static.xml^
   --protocol peppol-transport-as4-v2_0^
   -u "http://40.115.23.114:8080/domibus/services/msh?domain=static"`

When performing the test if the AP is configured correctly using this command:

`java -DOXALIS_HOME=C:/OXALIS_HOME/standalone^
   -classpath "C:/OXALIS_HOME/standalone/*;C:/OXALIS_HOME/as4/*"^
    eu.sendregning.oxalis.Main^
  -cert ceftestparty105gw.crt^
  -f payload_static.xml^
  --protocol peppol-transport-as4-v2_0^
  -u "http://peppol.sandbox.billit.be/as4"`

it works, so I'm assuming the AP is configured correct.
When changing the config to work with our own certificates everything also works.
But I just can't get the CEF Connectivity test to pass...

Can anyone point me in the right direction of what is going wrong?

**Comment by Kim-Billit** [comment]
The status of my AP is the folowing:
https://peppol.sandbox.billit.be/as4/status

version.oxalis.as4: 4.1.9
version.java: 1.8.0_191
mode: TEST

**Comment by FrodeBjerkholt** [comment]
The <eb:ErrorDetail>unknown error occurred</eb:ErrorDetail> is in the response fra the CEF connectivity test AP. You should ask CEF if they can see what is causing the problem on their side.

**Comment by Kim-Billit** [comment]
Thx, I have ask CEF if they can see anything.
I will add their answer to this issue once I get it.

**Comment by Kim-Billit** [comment]
This was the answer of CEF:

![image](https://user-images.githubusercontent.com/51436061/79554407-4e981800-809e-11ea-9d09-c35f9b5729aa.png)

To resolve this, I needed to change the contents of the payload.xml to this:

```
<?xml version="1.0" encoding="UTF-8"?>
<StandardBusinessDocument xmlns="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader">
    <StandardBusinessDocumentHeader>
        <HeaderVersion>1.0</HeaderVersion>
        <Sender>
            <!-- This Sender section describes the PEPPOL Sender -->
            <!-- It corresponds to an OriginalSender in AS4 -->
          <Identifier>urn:oasis:names:tc:ebcore:partyid-type:unregistered:C1</Identifier>
      </Sender>
      <Receiver>
           <!-- This Sender section describes the PEPPOL Receiver -->
           <!-- It corresponds to an FinalRecipient in AS4 -->
           <Identifier>urn:oasis:names:tc:ebcore:partyid-type:unregistered:C4</Identifier>
        </Receiver>
        <DocumentIdentification>
            <!-- This DocumentIdentification section describes the content of the payload -->
            <!-- It is noe essential to the CEF connectivity test, but is needed for a valid SBDH -->

            <Standard>NONE</Standard>
            <TypeVersion>1.0</TypeVersion>
            <InstanceIdentifier>a3140ce5-7c03-432c-a373-cab9c5dd9560</InstanceIdentifier>
            <Type>CEF Connectivity test</Type>
            <CreationDateAndTime>2020-04-16T12:03:00.000+02:00</CreationDateAndTime>
        </DocumentIdentification>
        <BusinessScope>
            <Scope>
                <!-- This Scope section describes the PEPPOL DocumentType -->
                <!-- It corresponds to an Action in AS4 (PMode[1].BusinessInfo.Action) -->

                <Type>DOCUMENTID</Type>
                <!-- We add an empty Identifier element to set the 'DocumentIdentifier Schema' to en empty string -->
                <!-- If we do not do this Oxalis-Standalone will add a default 'DocumentType Schema' that will prefix the Action with "busdox-docid-qns", or what is defined in this element, and "::" -->
                <Identifier/>
                <InstanceIdentifier>connectivity::cef##connectivity::submitMessage</InstanceIdentifier>
            </Scope>
            <Scope>
                <!-- This Scope section describes the PEPPOL Process -->
                <!-- It corresponds to an Service in AS4 (PMode[1].BusinessInfo.Service) -->

                <Type>PROCESSID</Type>
                <!-- This Identifier describes the PEPPOL 'Process Schema' and corresponds to a Service.Type in AS4 (PMode[].BusinessInfo.Service.type) -->
                <Identifier>e-delivery</Identifier>
                <!-- This InstanceIdentifier describes the PEPPOL 'Process Value' and corresponds to an Service in AS4 (PMode[1].BusinessInfo.Service) -->
                <InstanceIdentifier>http://ec.europa.eu/e-delivery/services/connectivity-service</InstanceIdentifier>
            </Scope>
        </BusinessScope>
    </StandardBusinessDocumentHeader>
    <Request> eDelivery AS4 Connectivity test. Sending Message </Request>
</StandardBusinessDocument>
```

Where the Identifiers of the sender and Receiver does not need to be the PartyID's received by the CEF but should just be C1 and C4.

To define the correct sender and receiver I also needed add the sender and receiver in the command, like this:

```
java -DOXALIS_HOME=C:/OXALIS_HOME^
   -classpath "standalone/*;as4/*"^
   eu.sendregning.oxalis.Main^
   -cert cefsupportgw.cer^
   -s ceftestparty105gw^
   -r cefsupportgw^
   -f payload_static.xml^
   --protocol peppol-transport-as4-v2_0^
   -u "http://40.115.23.114:8080/domibus/services/msh?domain=static"
```

When performing the test like this is was successful.

Maybe this can be added to the tutorial?
https://github.com/difi/Oxalis-AS4/blob/master/docs/cef-connectivity/index.md

**Comment by FrodeBjerkholt** [comment]
Thanks for the information. Maybe they have changed something lately? I will retry the connectivity test and update the documentation accordingly.

**Comment by FrodeBjerkholt** [comment]
Hmm. I retried the connectivity test as described in the documentation and it worked perfectly. But I will change the documentation as you described, because I think it is more correct.
