### ISSUE TITLE
Identifier 'iso6523-actorid-upis::0088:xxxx' is not registered in SML

### ISSUE THREAD

**Issue by abaigelcom** [OxalisCommunity/Oxalis-AS4#127]
Hi,
We are able to integrate AS4 libs to our tomcat deployment and it is working as expected but with little tweak.
The oxalis release version used: 4.1.2 and AS4 4.1.9
our test identifier is registered [here](https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?scheme=iso6523-actorid-upis&value=0088%3Aelcom-test&sml=auto&querybc=true&__querybc=true&__showtime=true&xsdvalidation=true&__xsdvalidation=true&verifysignatures=true&__verifysignatures=true&action=perform)
But getting below error that its not a registered identifier until we specify the below properties in oxalis.conf

mode.conformance=test
mode.conformance.lookup.locator.hostname="acc.edelivery.tech.ec.europa.eu/edelivery-sml/"

The above properties are mandatory to work?
If this is true then what will be for PROD? 
mode.conformance=PROD
mode.conformance.lookup.locator.hostname="edelivery.tech.ec.europa.eu/edelivery-sml/"

Stack trace below.

Detected mode: TEST
Prioritized list of transport profiles:
=> peppol-transport-as4-v2_0
=> busdox-transport-as2-ver1p0r1
=> busdox-transport-as2-ver2p0
=> busdox-transport-as2-ver1p0
2020-07-28 23:20:28,331 INFO c.e.p.g.o.o.OxalisOutboundTransmitter [http-nio-8080-exec-6] isOverrideAllowed of RequestBuilder: false
2020-07-28 23:20:44,506 ERROR c.e.p.g.o.o.OxalisOutboundTransmitter [http-nio-8080-exec-6] Error in transmit: Identifier 'iso6523-actorid-upis::0088:elcom-test' is not registered in SML.
Caused by: no.difi.vefa.peppol.lookup.api.LookupException: Identifier 'iso6523-actorid-upis::0088:elcom-test' is not registered in SML.
        at no.difi.vefa.peppol.lookup.locator.BdxlLocator.lookup(BdxlLocator.java:105) ~[peppol-lookup-1.1.4.jar:?]
        at no.difi.vefa.peppol.lookup.LookupClient.getServiceMetadata(LookupClient.java:80) ~[peppol-lookup-1.1.4.jar:?]
        at no.difi.vefa.peppol.lookup.LookupClient.getEndpoint(LookupClient.java:114) ~[peppol-lookup-1.1.4.jar:?]
        at no.difi.oxalis.outbound.lookup.CachedLookupService.load(CachedLookupService.java:79) ~[oxalis-outbound-4.1.2.jar:?]
        at no.difi.oxalis.outbound.lookup.CachedLookupService.load(CachedLookupService.java:46) ~[oxalis-outbound-4.1.2.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[guava-28.2-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[guava-28.2-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[guava-28.2-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[guava-28.2-jre.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951) ~[guava-28.2-jre.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974) ~[guava-28.2-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958) ~[guava-28.2-jre.jar:?]
        at no.difi.oxalis.outbound.lookup.CachedLookupService.lookup(CachedLookupService.java:71) ~[oxalis-outbound-4.1.2.jar:?]

**Comment by SuperJuell** [comment]
Test environment. Please make sure this endpoint is available in SMK
