### ISSUE TITLE
How to resolve error message "Please check the message header"

### ISSUE THREAD

**Issue by amaters-easy** [OxalisCommunity/Oxalis-AS4#142]
Hello, 

We are currently running tests with the new GITB testbed and experiencing problems with sending (receiving was successful). 
Is there any experience who can help us with this problem?

Problem

We are using Oxalis AS4 4.1.9.

The Oxalis configuration:
oxalis.keystore {
     # Relative to OXALIS_HOME
     path=einvoicingct_37_gwkeystore.jks
     password = XXXXX
     key.alias = einvoicingct_37_gw
     key.password = XXXX
}

security.truststore.ap = gateway_truststore.jks
security.truststore.password=XXXXX

Below the settings we use for sending and attached the payload we send. 

java -classpath "/oxalis/conf/*:/oxalis/lib-standalone/*:/oxalis/lib/*:/oxalis/ext/*" eu.sendregning.oxalis.Main -cert /oxalis/conf/gateway_truststore.cer -s einvoicingct_37_gw -r domibus-gitb -f /storage/output/einvoicingct_37_gw/domibus-gitb/payload.xml --protocol peppol-transport-as4-v2_0 -u https://www.itb.ec.europa.eu/cef/domibus/services/msh

We are in doubt about the certificates we are using. 

I hope you can help. Thanks! 
If you need more information, please let me know! 

Logs
020-11-20 15:25:14,638 ERROR [eu.sendregning.oxalis.Main] [] Execution failed: no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: Fajava.util.concurrent.ExecutionException: no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: Failed to send message
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at eu.sendregning.oxalis.Main.main(Main.java:225)
Caused by: no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: Failed to send message
at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:108)
at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:89)
at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:166)
at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:94)
at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:48)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.ws.soap.SOAPFaultException: An error occurred while processing your request. Please check the message header for more at org.apache.cxf.jaxws.DispatchImpl.mapException(DispatchImpl.java:285)
at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:330)
at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:105)
... 14 common frames omitted
Caused by: org.apache.cxf.binding.soap.SoapFault: An error occurred while processing your request. Please check the message header for mor at org.apache.cxf.binding.soap.interceptor.Soap12FaultInInterceptor.unmarshalFault(Soap12FaultInInterceptor.java:156)
at org.apache.cxf.binding.soap.interceptor.Soap12FaultInInterceptor.handleMessage(Soap12FaultInInterceptor.java:66)
at org.apache.cxf.binding.soap.interceptor.Soap12FaultInInterceptor.handleMessage(Soap12FaultInInterceptor.java:52)
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:112)
at org.apache.cxf.binding.soap.interceptor.CheckFaultInterceptor.handleMessage(CheckFaultInterceptor.java:70)
at org.apache.cxf.binding.soap.interceptor.CheckFaultInterceptor.handleMessage(CheckFaultInterceptor.java:35)
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:829)
at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1693)
at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1570)
at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1371)
at org.apache.cxf.ext.logging.LoggingOutputStream.postClose(LoggingOutputStream.java:53)
at org.apache.cxf.io.CachedOutputStream.close(CachedOutputStream.java:228)
at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:671)
at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java: at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)

**Comment by amaters-easy** [comment]
going to close this one. certificates are fine and we now have more understanding about the issue. will create a new more specific one if needed
