### ISSUE TITLE
Docker container crashes at startup

### ISSUE THREAD

**Issue by vmax** [OxalisCommunity/Oxalis-AS4#156]
**UPD**: this is caused by OxalisCommunity/oxalis#518

Attempting to start `norstella/oxalis-as4:5.0.1` image (latest at the time) throws an error:

```
2021-05-29 19:01:52,392  INFO [network.oxalis.server.Main] Starting server 
Exception in thread "main" java.lang.IllegalStateException: StatisticsHandler has no Wrapped Handler
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:251)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at network.oxalis.server.Main.run(Main.java:82)
	at network.oxalis.server.Main.main(Main.java:58)
```

I'm starting the container by bind-mounting keystore file & a config which only contains `oxalis.keystore` section (for passing in password)

**Comment by aaron-kumar** [comment]
Docker images are created with the contribution of members like you @vmax . 

We are not actively supporting docker images due to limitation of budget. Our main purpose is to support core components and we are relying on contributors to provide extensions. So you are free to raise PR (as you did: https://github.com/OxalisCommunity/oxalis/pull/519 ) 

Below are repository hosting Oxalis and Oxalis-AS4:
- Oxalis: https://hub.docker.com/r/norstella/oxalis/tags
- Oxalis-AS4: https://hub.docker.com/r/norstella/oxalis-as4/tags

**Note**: Norstella is just hosting docker images and we are not scanning these images as of now (probably in future, but not now). So please take necessary precautions when using these images.
