### ISSUE TITLE
Cann't get it working

### ISSUE THREAD

**Issue by pschoond** [OxalisCommunity/Oxalis-AS4#162]
Hi,

We're succesfully running oxalis 4.1.2 as a .war. container in Tomcat, on CentOS 8. Now I need to get this as4 addon working but Oxalis won't run anymore when I follow the instructions in the installation manual for Tomcat8+. As soon as I define the oxalis.xml file with the .war file and as4 directory, Oxalis does not start anymore. It seems to loose the classpath, as far as I understand. This is the output of localhost.log:
=============================================
27-Jun-2021 16:00:23.637 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Error configuring application listener of class [no.difi.oxali
s.dist.war.WarServletContextListener]
        java.lang.NoClassDefFoundError: network/oxalis/commons/guice/OxalisModule
                at java.lang.ClassLoader.defineClass1(Native Method)
                at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
                at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
                at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2432)
                at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:865)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1334)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
                at java.lang.Class.forName0(Native Method)
                at java.lang.Class.forName(Class.java:264)
                at no.difi.oxalis.commons.guice.GuiceModuleLoader.loadModule(GuiceModuleLoader.java:133)
                at no.difi.oxalis.commons.guice.GuiceModuleLoader.load(GuiceModuleLoader.java:128)
                at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
                at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
                at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628)
                at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
                at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
                at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
                at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
                at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
                at no.difi.oxalis.commons.guice.GuiceModuleLoader.getModules(GuiceModuleLoader.java:115)
                at no.difi.oxalis.commons.guice.GuiceModuleLoader.initiate(GuiceModuleLoader.java:62)
                at no.difi.oxalis.inbound.OxalisGuiceContextListener.<init>(OxalisGuiceContextListener.java:45)
                at no.difi.oxalis.dist.war.WarServletContextListener.<init>(WarServletContextListener.java:11)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:151)
                at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4640)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5177)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:706)
                at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:631)
                at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1830)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
                at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:526)
                at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425)
                at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
                at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
                at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
                at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
                at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
                at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
                at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
        Caused by: java.lang.ClassNotFoundException: network.oxalis.commons.guice.OxalisModule
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1365)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
                ... 69 more
27-Jun-2021 16:00:23.653 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Skipped installing application listeners due to previous error(s)
=============================================

oxalis.xml:
=============================================
<?xml version="1.0" encoding="UTF-8"?>

<Context docBase="/opt/oxalis/oxalis.war"  >
    
   
   <Environment name="OXALIS_HOME" value="/opt/oxalis/home" type="java.lang.String" override="false" />

    
   
   <Resources className="org.apache.catalina.webresources.ExtractingRoot">
            
      

      <PreResources 
          base="/opt/oxalis" 
          className="org.apache.catalina.webresources.DirResourceSet"
          webAppMount="/WEB-INF/lib"
          readOnly="true" />
    
      
      <PostResources
        base="/opt/oxalis/as4" 
        className="org.apache.catalina.webresources.DirResourceSet"
        webAppMount="/WEB-INF/lib"
        />  
      
      
      
      
      
   </Resources>

</Context>
===========================================

- the download links in the install document are dead. I found the nessessary files in search.maven.org
- cann't find information about versions; do I need to upgrade oxalis to version 5.03 to be able to run as4 version 5.03 ?
- the <PreResources part in the oxalis is commented out in the example. Not sure if this is needed (?)
- Tomcat was installed from a package repository (tomcat-9.0.39-2.el8.lux.noarch) for upgrade support reasons (I now this is not recommended but works just as well)
- Also tried the oxalis-server. Copied the as4 files to the ext directory but also stops working then with class errors.

What am I missing ???

Thanks in advance for your help.

**Comment by pschoond** [comment]
oxalis.xlm 

`<?xml version="1.0" encoding="UTF-8"?>








<Context docBase="/opt/oxalis/oxalis.war"  >
    
   
   <Environment name="OXALIS_HOME" value="/opt/oxalis/home" type="java.lang.String" override="false" />

    
   
   <Resources className="org.apache.catalina.webresources.ExtractingRoot">
            
      

      <PreResources 
          base="/opt/oxalis" 
          className="org.apache.catalina.webresources.DirResourceSet"
          webAppMount="/WEB-INF/lib"
          readOnly="true" />
    
      
      <PostResources
        base="/opt/oxalis/as4" 
        className="org.apache.catalina.webresources.DirResourceSet"
        webAppMount="/WEB-INF/lib"
        />  
      
      
      
      
      
   </Resources>

</Context>`

**Comment by pschoond** [comment]
How do I paste the xml file here ? It gets cut off halfway.

**Comment by SuperJuell** [comment]
> How do I paste the xml file here ? It gets cut off halfway.

Hi, and welcome to the Oxalis community! Not the best solution, but you could of course just paste in part two of your XML in a new post.

**Comment by pschoond** [comment]
Thanks SuperJuell, (although I've posted to the oxalis community before).
Good thought. Got me to the idea of putting it between quotes, et voilat...

oxalis.xml:
=============================
“””<?xml version="1.0" encoding="UTF-8"?> 
 
 
 

 
 
 
<Context docBase="/opt/oxalis/oxalis.war"  > 
    
   
  <Environment name="OXALIS_HOME" value="/opt/oxalis/home" type="java.lang.String" override="false" /> 

    
   
  <Resources className="org.apache.catalina.webresources.ExtractingRoot"> 
            
      

     <PreResources  
         base="/opt/oxalis"  
         className="org.apache.catalina.webresources.DirResourceSet" 
         webAppMount="/WEB-INF/lib" 
         readOnly="true" /> 
    
      
     <PostResources 
       base="/opt/oxalis/as4"  
       className="org.apache.catalina.webresources.DirResourceSet" 
       webAppMount="/WEB-INF/lib" 
       />   
      
      
      
      
      
  </Resources> 
</Context>”””
==================================

**Comment by pschoond** [comment]
`<?xml version="1.0" encoding="UTF-8"?> 
 
 
 

 
 
 
<Context docBase="/opt/oxalis/oxalis.war"  > 
    
   
  <Environment name="OXALIS_HOME" value="/opt/oxalis/home" type="java.lang.String" override="false" /> 

    
   
  <Resources className="org.apache.catalina.webresources.ExtractingRoot"> 
            
      

     <PreResources  
         base="/opt/oxalis"  
         className="org.apache.catalina.webresources.DirResourceSet" 
         webAppMount="/WEB-INF/lib" 
         readOnly="true" /> 
    
      
     <PostResources 
       base="/opt/oxalis/as4"  
       className="org.apache.catalina.webresources.DirResourceSet" 
       webAppMount="/WEB-INF/lib" 
       />   
      
      
      
      
      
  </Resources> 
</Context>”””
`

**Comment by pschoond** [comment]
Here is our oxalis.xml in pdf format:
[oxalis.pdf](https://github.com/OxalisCommunity/Oxalis-AS4/files/6724236/oxalis.pdf)

**Comment by pschoond** [comment]
Found the solution, it needs oxalis-5.0x. Tested with 5.03 oxalis distribution downloaded from 
https://repo1.maven.org/maven2/network/oxalis/oxalis-distribution/5.0.3/oxalis-distribution-5.0.3-distro.tar.gz on a test server.

Can this be mentioned as a prerequisite in the documentation please ?

Also, can I upgrade from 4.2.1 to 5.03 on production without expecting problems ?

**Comment by aaron-kumar** [comment]
>> cann't find information about versions; do I need to upgrade oxalis to version 5.03 to be able to run as4 version 5.03 ?
Yes, oxalis-as4 is making use of Oxalis dependency. With Version 5.0.0, there was change in  GroupID, Package name  etc, so Oxalis-as4 5.x can't work with any Oxalis version lower than 5.x. Documentation is updated accordingly : https://github.com/OxalisCommunity/Oxalis-AS4 (Refer README file)

Oxalis 5.0.1 & 5.0.3 already in production use. 
Latest Oxalis-AS4 version:  https://github.com/OxalisCommunity/Oxalis-AS4/releases/tag/v5.0.2
