### ISSUE TITLE
Message failed : Unable to find active endpoint information for given transport profile(s).

### ISSUE THREAD

**Issue by pasbos** [OxalisCommunity/Oxalis-AS4#176]
Going through the tests of the OpenPeppol testbed, I fail at the second step (Testing AP sends back to Testbed).

oxalis-war (5.0.7 - build from source) is running and can receive invoices.

The jar files of oxalis-as4 (5.0.5 - v) are located in the folder as4

oxalis-standalone (5.0.7 build from source) has a separate configuration with the attributes for oxalis.keystore - nothing more

I start the command:
```
java -DOXALIS_HOME=/home/peppol/.oxalis/standalone/ -cp "standalone/*:as4/*" eu.sendregning.oxalis.Main -f ~/OUT/altered_file.xml
```

and get the following output:
```
2022-01-20 13:07:29,006 INFO [network.oxalis.commons.filesystem.detector.PropertyHomeDetector] Using Oxalis folder specified as Java System Property '-D OXALIS_HOME' with value '/home/peppol/.oxalis/standalone/'.
2022-01-20 13:07:29,015 INFO [network.oxalis.commons.filesystem.FileSystemModule] Home folder: /home/peppol/.oxalis/standalone
2022-01-20 13:07:29,016 INFO [network.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /home/peppol/.oxalis/standalone
2022-01-20 13:07:29,016 INFO [network.oxalis.commons.config.ConfigModule] Configuration file: /home/peppol/.oxalis/standalone/oxalis.conf
2022-01-20 13:07:29,026 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => CONF:
2022-01-20 13:07:29,026 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: inbound
2022-01-20 13:07:29,026 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: <null>
2022-01-20 13:07:30,471 INFO [network.oxalis.commons.filesystem.detector.PropertyHomeDetector] Using Oxalis folder specified as Java System Property '-D OXALIS_HOME' with value '/home/peppol/.oxalis/standalone/'.
2022-01-20 13:07:30,471 INFO [network.oxalis.commons.filesystem.FileSystemModule] Home folder: /home/peppol/.oxalis/standalone
2022-01-20 13:07:30,472 INFO [network.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /home/peppol/.oxalis/standalone
2022-01-20 13:07:30,472 INFO [network.oxalis.commons.config.ConfigModule] Configuration file: /home/peppol/.oxalis/standalone/oxalis.conf
2022-01-20 13:07:30,475 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_TOTAL: 20
2022-01-20 13:07:30,475 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_MAX_ROUTE: 2
2022-01-20 13:07:30,475 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_VALIDATE_AFTER_INACTIVITY: 1000
2022-01-20 13:07:30,475 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_TIME_TO_LIVE: 30
2022-01-20 13:07:30,475 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_CONNECT: 0
2022-01-20 13:07:30,475 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_READ: 0
2022-01-20 13:07:30,475 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_SOCKET: 0
2022-01-20 13:07:30,475 INFO [network.oxalis.commons.settings.SettingsBuilder] Error => TRACKER: quiet
2022-01-20 13:07:30,475 INFO [network.oxalis.commons.settings.SettingsBuilder] AS2 => NOTIFICATION: not.in.use@difi.no
2022-01-20 13:07:30,476 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => CONF:
2022-01-20 13:07:30,476 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: inbound
2022-01-20 13:07:30,476 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: <null>
2022-01-20 13:07:30,476 INFO [network.oxalis.commons.settings.SettingsBuilder] Identifiers => HOSTNAME:
2022-01-20 13:07:30,476 INFO [network.oxalis.commons.settings.SettingsBuilder] Identifiers => MSGID_GENERATOR: default
2022-01-20 13:07:30,477 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => PATH: ***************************
2022-01-20 13:07:30,478 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => PASSWORD: ***************************
2022-01-20 13:07:30,478 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => KEY_ALIAS: cert
2022-01-20 13:07:30,479 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => KEY_PASSWORD: ***************************
2022-01-20 13:07:30,479 INFO [network.oxalis.commons.settings.SettingsBuilder] Header => PARSER: sbdh
2022-01-20 13:07:30,479 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => PAYLOAD: default
2022-01-20 13:07:30,480 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => RECEIPT: default
2022-01-20 13:07:30,480 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => EXCEPTION: default
2022-01-20 13:07:30,480 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => HANDLER: default
2022-01-20 13:07:30,480 INFO [network.oxalis.commons.settings.SettingsBuilder] Tracing => REPORTER: noop
2022-01-20 13:07:30,480 INFO [network.oxalis.commons.settings.SettingsBuilder] Tracing => HTTP: <null>
2022-01-20 13:07:30,480 INFO [network.oxalis.commons.settings.SettingsBuilder] Tracing => TRACER: noop
2022-01-20 13:07:30,481 INFO [network.oxalis.commons.settings.SettingsBuilder] Executor => DEFAULT: 50
2022-01-20 13:07:30,481 INFO [network.oxalis.commons.settings.SettingsBuilder] Executor => STATISTICS: 50
2022-01-20 13:07:30,481 INFO [network.oxalis.commons.settings.SettingsBuilder] Tag => GENERATOR: noop
2022-01-20 13:07:30,481 INFO [network.oxalis.commons.settings.SettingsBuilder] Timestamp => SERVICE: system
2022-01-20 13:07:30,482 INFO [network.oxalis.commons.settings.SettingsBuilder] Evidence => SERVICE: rem
2022-01-20 13:07:30,482 INFO [network.oxalis.commons.settings.SettingsBuilder] Transformer => DETECTOR: noop
2022-01-20 13:07:30,483 INFO [network.oxalis.commons.settings.SettingsBuilder] Transformer => WRAPPER: xml
2022-01-20 13:07:30,483 INFO [network.oxalis.commons.settings.SettingsBuilder] Statistics => SERVICE: noop
2022-01-20 13:07:30,484 INFO [network.oxalis.commons.settings.SettingsBuilder] Transmission => VERIFIER: default
2022-01-20 13:07:30,485 INFO [network.oxalis.commons.settings.SettingsBuilder] AS4 => HOSTNAME:
2022-01-20 13:07:30,485 INFO [network.oxalis.commons.settings.SettingsBuilder] AS4 => MSGID_GENERATOR: default
2022-01-20 13:07:30,486 INFO [network.oxalis.commons.settings.SettingsBuilder] AS4 => TYPE: peppol
2022-01-20 13:07:30,487 INFO [network.oxalis.commons.settings.SettingsBuilder] Logging => CONFIG: <null>
2022-01-20 13:07:30,487 INFO [network.oxalis.commons.settings.SettingsBuilder] Logging => SERVICE: logback
2022-01-20 13:07:30,570 INFO [network.oxalis.commons.security.CertificateModule] Certificate subject: CN=PDE000457, OU=PEPPOL TEST AP, O=***************************, C=***************************
2022-01-20 13:07:30,571 INFO [network.oxalis.commons.security.CertificateModule] Certificate issuer: CN=PEPPOL ACCESS POINT TEST CA - G2, OU=FOR TEST ONLY, O=OpenPEPPOL AISBL, C=BE
2022-01-20 13:07:31,442 INFO [network.oxalis.vefa.peppol.security.ModeDetector] Detected mode: TEST
2022-01-20 13:07:31,452 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] Prioritized list of transport profiles:
2022-01-20 13:07:31,455 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => peppol-transport-as4-v2_0
2022-01-20 13:07:31,455 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1
2022-01-20 13:07:31,455 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver2p0
2022-01-20 13:07:31,455 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0



Message failed : Unable to find active endpoint information for given transport profile(s).

2022-01-20 13:07:34,808 ERROR [eu.sendregning.oxalis.Main] Execution failed: network.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
java.util.concurrent.ExecutionException: network.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at eu.sendregning.oxalis.Main.main(Main.java:225)
Caused by: network.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at network.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:116)
        at network.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:166)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:94)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:48)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Total time spent: 3s
Attempted to send 0 files
Failed transmissions: 1
```

What am I doing wrong? What additional info can I provide?

**Comment by aaron-kumar** [comment]
@pasbos  : Please see message 
>  Message failed : Unable to find active endpoint information for given transport profile(s).
It says that there is problem with SMP registration. The document profile that you are trying to send is not published/registered in SMP with given transport Profile (in your case AS4/ peppol-transport-as4-v2_0)

**Comment by aaron-kumar** [comment]
@pasbos  do let me know if you have additional question or need any clarification. 
If you still have any doubt, please share relevant participant identifier so that I explain it with example. 

Note: Issue will be automatically closed if we do not hear anything from you soon.

**Comment by pasbos** [comment]
Thank you very much for your reply. 

Please give me a few more days to see if I can get the error fixed by adjusting my SMP (which I assume I can). 
I will then report back here.

**Comment by pasbos** [comment]
I tried to configure my smp with given transport profile. Now I'm getting this error:

```
2022-02-10 18:19:30,709 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] Prioritized list of transport profiles:
2022-02-10 18:19:30,710 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => peppol-transport-as4-v2_0
2022-02-10 18:19:30,710 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1
2022-02-10 18:19:30,710 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver2p0
2022-02-10 18:19:30,710 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0


2022-02-10 18:19:32,902 WARN [org.apache.cxf.ws.policy.AssertionBuilderRegistryImpl] No assertion builder for type {http://oxalis.network/custom/security-policy}Basic128GCMSha256MgfSha256 registered.
2022-02-10 18:19:33,755 WARN [org.apache.cxf.phase.PhaseInterceptorChain] Interceptor for {oxalis.network/}outbound-service#{http://cxf.apache.org/jaxws/dispatch}Invoke has thrown exception, unwinding now
org.apache.cxf.binding.soap.SoapFault: Problem writing SAAJ model to stream: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:224)
        at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:174)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
        at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)
        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
        at network.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:105)
        at network.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:89)
        at network.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
        at network.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
        at network.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
        at network.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:166)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:94)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:48)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.ctc.wstx.exc.WstxIOException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:471)
        at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:770)
        at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:716)
        at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:214)
        ... 24 common frames omitted
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:214)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1958)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1915)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1898)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1419)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1396)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1282)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1257)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.setupWrappedStream(URLConnectionHTTPConduit.java:274)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleHeadersTrustCaching(HTTPConduit.java:1343)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.onFirstWrite(HTTPConduit.java:1304)
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.onFirstWrite(URLConnectionHTTPConduit.java:307)
        at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:47)
        at org.apache.cxf.io.AbstractThresholdOutputStream.unBuffer(AbstractThresholdOutputStream.java:89)
        at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:63)
        at org.apache.cxf.io.CacheAndWriteOutputStream.write(CacheAndWriteOutputStream.java:80)
        at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:51)
        at com.ctc.wstx.io.UTF8Writer.write(UTF8Writer.java:143)
        at com.ctc.wstx.sw.BufferingXmlWriter.writeRaw(BufferingXmlWriter.java:286)
        at com.ctc.wstx.sw.BufferingXmlWriter.writeCharacters(BufferingXmlWriter.java:600)
        at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:469)
        ... 27 common frames omitted
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90)
        at sun.security.validator.Validator.getInstance(Validator.java:179)
        at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
        at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1508)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:215)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1024)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:954)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1065)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1384)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1412)
        ... 46 common frames omitted
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
        at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
        at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)
        ... 58 common frames omitted
2022-02-10 18:19:33,766 ERROR [eu.sendregning.oxalis.Main] Execution failed: network.oxalis.as4.lang.OxalisAs4TransmissionException: Failed to send message
java.util.concurrent.ExecutionException: network.oxalis.as4.lang.OxalisAs4TransmissionException: Failed to send message
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at eu.sendregning.oxalis.Main.main(Main.java:225)
Caused by: network.oxalis.as4.lang.OxalisAs4TransmissionException: Failed to send message
        at network.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:108)
        at network.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:89)
        at network.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
        at network.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
        at network.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
        at network.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:166)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:94)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:48)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.ws.soap.SOAPFaultException: Problem writing SAAJ model to stream: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at org.apache.cxf.jaxws.DispatchImpl.mapException(DispatchImpl.java:285)
        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:330)
        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
        at network.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:105)
        ... 14 common frames omitted
Caused by: org.apache.cxf.binding.soap.SoapFault: Problem writing SAAJ model to stream: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:224)
        at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:174)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
        at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)
        ... 16 common frames omitted
Caused by: com.ctc.wstx.exc.WstxIOException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:471)
        at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:770)
        at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:716)
        at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:214)
        ... 24 common frames omitted
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:214)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1958)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1915)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1898)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1419)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1396)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1282)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1257)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.setupWrappedStream(URLConnectionHTTPConduit.java:274)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleHeadersTrustCaching(HTTPConduit.java:1343)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.onFirstWrite(HTTPConduit.java:1304)
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.onFirstWrite(URLConnectionHTTPConduit.java:307)
        at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:47)
        at org.apache.cxf.io.AbstractThresholdOutputStream.unBuffer(AbstractThresholdOutputStream.java:89)
        at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:63)
        at org.apache.cxf.io.CacheAndWriteOutputStream.write(CacheAndWriteOutputStream.java:80)
        at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:51)
        at com.ctc.wstx.io.UTF8Writer.write(UTF8Writer.java:143)
        at com.ctc.wstx.sw.BufferingXmlWriter.writeRaw(BufferingXmlWriter.java:286)
        at com.ctc.wstx.sw.BufferingXmlWriter.writeCharacters(BufferingXmlWriter.java:600)
        at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:469)
        ... 27 common frames omitted
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90)
        at sun.security.validator.Validator.getInstance(Validator.java:179)
        at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
        at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1508)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:215)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1024)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:954)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1065)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1384)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1412)
        ... 46 common frames omitted
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
        at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
        at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)
        ... 58 common frames omitted
Total time spent: 2s
Attempted to send 0 files
Failed transmissions: 1
```

**Comment by aaron-kumar** [comment]
@pasbos : This is not Oxalis bug. There seems to be issue with cacerts/ Java setup.
In order to reproduce or better guide please share more details cacerts & OS, participant identifier etc.. 

Note: I am converting this issue to discussion as this is not bug. You will get support as part of discussion.
