### ISSUE TITLE
Standalone, Unable to detect MODE during CEF Connectivity Test (dynamic scenario)

### ISSUE THREAD

**Issue by aleixmoreno** [OxalisCommunity/Oxalis-AS4#184]
Hi
I'm trying to pass the CEF Connectivity Test (dynamic scenario) sending the message with the StandAlone solucion, but I can't find the configuration to succes it, all the time Oxalis send me an error Validation of subject principal(CN) failed.
I can send it, with the certificate that Peppol send me for acceptation, and I can do all test and all work fine, is only with the certificate that CEF send me to pass the test that I can't find the solution.

I conntacted with CEF saing this but they don't give me a solucion

Could someone help me with it?

Thanks!!

**Conf**
----------------------------------
oxalis.truststore {
     password =xxx
     path = gateway_truststore.jks

}
oxalis.keystore {
	# Relative to OXALIS_HOME
	path = xxxxxx
	password = xxxxx
	key.alias = xxxxx
	key.password =xxxxxx
}
lookup.locator.hostname	= "acc.edelivery.tech.ec.europa.eu/edelivery-sml/"
oxalis.as4.type				= cef-connectivity
oxalis.path.inbound			= "C:\\oxalis\\spi4WS\\IN"  #\oxalis\spi4WS\IN
oxalis.path.inbound			= "C:\\oxalis\\spi4WS\\OUT"  #\oxalis\spi4WS\OUT
----------------------------------

**Log:**
----------------------------------
INFO [network.oxalis.commons.security.CertificateModule] [] Certificate issuer: EMAILADDRESS=CEF-EDELIVERY-SUPPORT@ec.europa.eu, CN=Connectivity Test Component CA, OU=Connecting Europe Facility, O=Connectivity Test, ST=Belgium, C=BE 
INFO [network.oxalis.vefa.peppol.security.ModeDetector] [] Detection error (TEST): **Validation of subject principal(CN) failed**. 
INFO [network.oxalis.vefa.peppol.security.ModeDetector] [] Detection error (LOCAL): Certificate should be self-signed. 
INFO [network.oxalis.vefa.peppol.security.ModeDetector] [] Detection error (PRODUCTION): **Validation of subject principal(CN) failed**. 
INFO [network.oxalis.outbound.transmission.MessageSenderFactory] [] Prioritized list of transport profiles: 
INFO [network.oxalis.outbound.transmission.MessageSenderFactory] [] => **peppol-transport-as4-v2_0** 
INFO [network.oxalis.outbound.transmission.MessageSenderFactory] [] => busdox-transport-as2-ver1p0r1 
INFO [network.oxalis.outbound.transmission.MessageSenderFactory] [] => busdox-transport-as2-ver2p0 
INFO [network.oxalis.outbound.transmission.MessageSenderFactory] [] => busdox-transport-as2-ver1p0 
INFO [network.oxalis.vefa.peppol.security.ModeDetector] [] Detection error (TEST): Validation of subject principal(CN) failed. 
INFO [network.oxalis.vefa.peppol.security.ModeDetector] [] Detection error (LOCAL): Certificate should be self-signed. 
INFO [network.oxalis.vefa.peppol.security.ModeDetector] [] Detection error (PRODUCTION): Validation of subject principal(CN) failed. 
ERROR [network.oxalis.commons.guice.GuiceModuleLoader] [] Unable to detect mode. 
network.oxalis.api.lang.OxalisLoadingException: Unable to detect mode.
	at network.oxalis.commons.mode.ModeProvider.get(ModeProvider.java:74)
	at network.oxalis.commons.mode.ModeProvider.get(ModeProvider.java:46)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at network.oxalis.commons.guice.GuiceModuleLoader.initiate(GuiceModuleLoader.java:66)
	at network.oxalis.outbound.OxalisOutboundComponent.<init>(OxalisOutboundComponent.java:45)
	at eu.sendregning.oxalis.Main.main(Main.java:114)
	at com.validatedid.sp4i.peppol.services.impl.OxalisServicesImpl.sendUBL(OxalisServicesImpl.java:176)
	at com.validatedid.sp4i.peppol.services.impl.OxalisServicesImpl.sendUBLbySMP(OxalisServicesImpl.java:134)
	at com.validatedid.sp4i.peppol.PeppolClient.send(PeppolClient.java:49)
	at com.validatedid.sp4i.TestPeppol.testPostSend(TestPeppol.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
**Caused by: network.oxalis.vefa.peppol.common.lang.PeppolLoadingException: Unable to detect mode for certificate** 'EMAILADDRESS=CEF-EDELIVERY-SUPPORT@ec.europa.eu, CN=xxxxxxx, OU=Connecting Europe Facility, O=Connectivity Test, ST=Brussels-Capital, C=BE'.
	at network.oxalis.vefa.peppol.security.ModeDetector.detect(ModeDetector.java:61)
	at network.oxalis.commons.mode.ModeProvider.get(ModeProvider.java:72)
	... 38 common frames omitted

**Comment by pierfrancesco72** [comment]
Hi Aleix,

if you have downloaded the latest version of the software, try adding these 2 properties to `oxalis.conf`:

```property
lookup.locator.class = network.oxalis.vefa.peppol.lookup.locator.BusdoxLocator
security.validator.class = network.oxalis.vefa.peppol.security.util.EmptyCertificateValidator
```

**Comment by aleixmoreno** [comment]
Hi Francesco!

Are you able pass the test with this changes?

Saturday someone answer to my question, but isn't really util

I need finish some task now but in few hour I restart work

Salutation



________________________________
De: pierfrancesco ***@***.***>
Enviado: lunes, 9 de mayo de 2022 11:12
Para: OxalisCommunity/Oxalis-AS4 ***@***.***>
Cc: Aleix Moreno ***@***.***>; Author ***@***.***>
Asunto: Re: [OxalisCommunity/Oxalis-AS4] Standalone, Unable to detect MODE, only during CEF Connectivity Test (Issue #184)


Hi Aleix,

if you have downloaded the latest version of the software, try adding these 2 properties to oxalis.conf:

lookup.locator.class = network.oxalis.vefa.peppol.lookup.locator.BusdoxLocator
security.validator.class = network.oxalis.vefa.peppol.security.util.EmptyCertificateValidator

**Comment by pierfrancesco72** [comment]
Hi Aleix,

try the configuration I described in this other topic:

https://github.com/OxalisCommunity/Oxalis-AS4/issues/179#issuecomment-1121058797

Although it is not yet successful :-(  but at least you are making progress.

Pierfrancesco

**Comment by eyop23** [comment]
Message failed : Content does not contain SBDH.

2024-12-08 14:38:45,870 ERROR [eu.sendregning.oxalis.Main] Execution failed: network.oxalis.api.lang.OxalisTransmissionException: No transmission is provided. 
java.util.concurrent.ExecutionException: network.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at eu.sendregning.oxalis.Main.main(Main.java:228)
Caused by: network.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at network.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:106)
        at network.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:96)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:157)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:90)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:52)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Total time spent: 0s
Attempted to send 0 files
Failed transmissions: 1
what about this issue?
i am working locally and my oxalis.conf file look like this
# Keystore configuration
oxalis.keystore {
    path = "/home/cool/Desktop/ap/oxalis/keystore.p12"
    password = "12345678"

    key {
        alias = "oxalis-key"
        password = "12345678"
    }
}

# Operational mode: test or production
oxalis.mode = "local"
lookup.locator.class = network.oxalis.vefa.peppol.lookup.locator.BusdoxLocator
security.validator.class = network.oxalis.vefa.peppol.security.util.EmptyCertificateValidator
# Service Metadata Locator (SML) for test environment
# oxalis.sml.url = "https://acc.edelivery.tech.ec.europa.eu/sml"

# Inbound HTTP listener settings
oxalis.inbound {
    port = 8080
    path = "/oxalis/inbound"
}
