### ISSUE TITLE
Issue with Document Delivery

### ISSUE THREAD

**Issue by SanjayasH** [OxalisCommunity/Oxalis-AS4#208]
Hello Team,

In our production environment, we are encountering failures when attempting to send documents to our customers.

While documents are being successfully delivered to most of the other customers, we are currently observing this failures only with few number of customers. Although we have been observing this issue for sometime with a specific customer, now the fail rate is gradually increasing as the document delivery fails for some other customers as well.

We hope that someone from Oxalis Team will help us to sort this out.

```
com.compello.b2b.oxalisout.service.InvalidTransmissionException: Failed to transmit file: 123456743.xml-67890123.xml after 5 attempts
    at com.compello.b2b.oxalisout.service.OxalisOutboundMessageDispatcher.transmit(OxalisOutboundMessageDispatcher.java:106)
    at com.compello.b2b.oxalisout.service.OxalisOutboundMessageDispatcher.dispatch(OxalisOutboundMessageDispatcher.java:77)
    at com.compello.b2b.oxalisout.service.FileProcessor.processFile(FileProcessor.java:39)
    at com.compello.b2b.oxalisout.service.FileProcessor.run(FileProcessor.java:89)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: Failed to send message
    at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:108)
    at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:89)
    at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
    at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
    at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
    at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:106)
    at com.compello.b2b.oxalisout.service.OxalisOutboundMessageDispatcher.transmit(OxalisOutboundMessageDispatcher.java:99)
    ... 8 common frames omitted
Caused by: javax.xml.ws.soap.SOAPFaultException: These policy alternatives can not be satisfied: 
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}X509Token: The received token does not match the token inclusion requirement
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}SignedParts: Soap Body is not SIGNED
    at org.apache.cxf.jaxws.DispatchImpl.mapException(DispatchImpl.java:285)
    at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:330)
    at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
    at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:105)
    ... 14 common frames omitted
Caused by: org.apache.cxf.ws.policy.PolicyException: These policy alternatives can not be satisfied: 
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}X509Token: The received token does not match the token inclusion requirement
{http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}SignedParts: Soap Body is not SIGNED
    at org.apache.cxf.ws.policy.AssertionInfoMap.checkEffectivePolicy(AssertionInfoMap.java:179)
    at org.apache.cxf.ws.policy.PolicyVerificationInInterceptor.handle(PolicyVerificationInInterceptor.java:102)
    at org.apache.cxf.ws.policy.AbstractPolicyInterceptor.handleMessage(AbstractPolicyInterceptor.java:44)
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
    at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:829)
    at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1693)
    at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1570)
    at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1371)
    at org.apache.cxf.ext.logging.LoggingOutputStream.postClose(LoggingOutputStream.java:53)
    at org.apache.cxf.io.CachedOutputStream.close(CachedOutputStream.java:228)
    at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
    at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:671)
    at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63)
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
    at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
    at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
    at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
    at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
    at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
    at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)
    ... 16 common frames omitted
```

**Comment by aaron-kumar** [comment]
@SanjayasH : I can see multiple problem with your integration. But since you mentioned that only few customers are affected so I need additional information to reach to conclusion. 

Possible causes:
1. Incompatible Oxalis & Oxalis-AS4 version
2. Configuration issue in Oxalis.conf 
3. Certificate related issue 

As per package name (no.difi.oxalis.as4.outbound), mentioned in stacktrace, it is clear that you are using quite older (<5.x) version of Oxalis-AS4 (There is no support available for Oxalis Version < 5.x) 

Can you list down version of following:
1. Oxalis
2. Oxalis-AS4 
3. Java 
4. Servlet Container (Tomcat etc) 

Also share oxalis.conf file (Hide/remove password related information)

Additionally, I can see two issues with same problem(Duplicate issue: https://github.com/OxalisCommunity/oxalis/issues/621). It is gentle advise to open only one issue per problem. Also try to search the solution of your problem from older/closed issues.

**Comment by SanjayasH** [comment]
Hi @aaron-kumar ,

Thank you for your prompt response.
Yes, we are using quite older version of Oxalis. Therefore we are currently working on updating Oxalis and Oxalis-AS4 to v5.5.0 in production.

Please find the following requested information:

1. Oxalis --> **4.1.2**
2. Oxalis-AS4 --> **4.1.9**
3. Java --> **1.8.0_241**
4. oxalis.conf -->

![image](https://github.com/OxalisCommunity/Oxalis-AS4/assets/128377299/f8fdeb2d-8d98-46a8-a157-7fb6e78a2afd)

I am truly sorry for raising two duplicate issues and I'll close the previous one. I went through few older problems before raising the issue, but I could not find a proper solution.

**Comment by aaron-kumar** [comment]
So in Production, you are using Oxalis : 4.1.2 and Oxalis-AS4 : 4.1.9 right? 
As I mentioned, there could be multiple reason for such error with older version. Unfortunately, it is difficult to provide support on such an old version. I recommended to upgrade to latest Oxalis & Oxalis-AS4 versions (say v5.5.0) ASAP . 

During upgrade to latest version, if you will face issue then please raise here.

**Comment by SanjayasH** [comment]
Yes @aaron-kumar, we are currently using Oxalis : 4.1.2 and Oxalis-AS4 : 4.1.9 in production. 
I will raise here if we face any issues when updating to the latest version.

Thank you.

**Comment by aaron-kumar** [comment]
@SanjayasH : I am changing this to discussion since this is Not an issue with Oxalis
