### ISSUE TITLE
Message failed : Validation of subject principal(CN) failed.

### ISSUE THREAD

**Issue by Sivasgebiz** [OxalisCommunity/Oxalis-AS4#216]
2023-09-09 14:09:03.170 DEBUG 908 --- [   scheduling-1] com.sgebiz.peppol.service.SftpConnect    : r (TEST): Validation of subject principal(CN) failed. 
2023-09-09 14:09:03,051 INFO [no.difi.vefa.peppol.security.ModeDetector] Detection error (LOCAL): Certificate should be self-signed. 

2023-09-09 14:09:04.170 DEBUG 908 --- [   scheduling-1] com.sgebiz.peppol.service.SftpConnect    : 2023-09-09 14:09:03,805 INFO [no.difi.vefa.peppol.security.ModeDetector] Detected mode: PRODUCTION 
2023-09-09 14:09:03,809 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] Prioritized list of transport profiles: 
2023-09-09 14:09:03,810 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => peppol-transport-as4-v2_0 
2023-09-09 14:09:03,810 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1 
2023-09-09 14:09:03,810 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver2p0 
2023-09-09 14:09:03,810 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0 

2023-09-09 14:09:05.170 DEBUG 908 --- [   scheduling-1] com.sgebiz.peppol.service.SftpConnect    : 
Message failed : Validation of subject principal(CN) failed.

2023-09-09 14:09:05,110 ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided. 
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at eu.sendregning.oxalis.Main.main(Main.java:225)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:116)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
	at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:166)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:94)
	at eu.sendregning.oxalis.TransmissionTask.call(Tra
2023-09-09 14:09:05.170 DEBUG 908 --- [   scheduling-1] com.sgebiz.peppol.service.SftpConnect    : nsmissionTask.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Total time spent: 1s
Attempted to send 0 files
Failed transmissions: 1

**Comment by aaron-kumar** [comment]
No enough information to reproduce... also based on package (no.difi.oxalis.api.... ) , you are using Oxalis version previous than Oxalis 5.0.0 which is No longer supported.

Converting this issue to discussion...
