### ISSUE TITLE
Error Sending Test Document Oxalis.Standalone

### ISSUE THREAD

**Issue by DioMeo** [OxalisCommunity/Oxalis-AS4#231]
Hello, I was thying to send a document for a test, after creating the new server.
I ran this command:

java -classpath "standalone/*:as4/*" eu.sendregning.oxalis.Main -f /var/peppol/OUT/DOCS/ee20f0d6-89f9-4ddd-8466-c62bc9d494b0_IT00967720285_OZ_P0207.xml

and I have this error:

2023-12-13 17:31:02,075 INFO [network.oxalis.commons.filesystem.detector.EnvironmentHomeDetector] Using Oxalis folder specified as environment variable 'OXALIS_HOME' with value '/opt/tomcat/.oxalis'.
2023-12-13 17:31:02,079 INFO [network.oxalis.commons.filesystem.FileSystemModule] Home folder: /opt/tomcat/.oxalis
2023-12-13 17:31:02,079 INFO [network.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /opt/tomcat/.oxalis
2023-12-13 17:31:02,079 INFO [network.oxalis.commons.config.ConfigModule] Configuration file: /opt/tomcat/.oxalis/oxalis.conf
2023-12-13 17:31:02,082 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => CONF:
2023-12-13 17:31:02,082 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: /var/peppol/IN
2023-12-13 17:31:02,083 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: <null>
2023-12-13 17:31:02,328 INFO [network.oxalis.as4.util.OxalisAlgorithmSuiteLoader] Registering OxalisAlgorithmSuite on bus cxf1413886135
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/var/peppol/OUT/standalone/oxalis-standalone.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2023-12-13 17:31:03,017 INFO [network.oxalis.commons.filesystem.detector.EnvironmentHomeDetector] Using Oxalis folder specified as environment variable 'OXALIS_HOME' with value '/opt/tomcat/.oxalis'.
2023-12-13 17:31:03,017 INFO [network.oxalis.commons.filesystem.FileSystemModule] Home folder: /opt/tomcat/.oxalis
2023-12-13 17:31:03,017 INFO [network.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /opt/tomcat/.oxalis
2023-12-13 17:31:03,017 INFO [network.oxalis.commons.config.ConfigModule] Configuration file: /opt/tomcat/.oxalis/oxalis.conf
2023-12-13 17:31:03,019 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_TOTAL: 20
2023-12-13 17:31:03,019 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_MAX_ROUTE: 2
2023-12-13 17:31:03,019 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_VALIDATE_AFTER_INACTIVITY: 1000
2023-12-13 17:31:03,019 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_TIME_TO_LIVE: 30
2023-12-13 17:31:03,019 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_CONNECT: 0
2023-12-13 17:31:03,019 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_READ: 0
2023-12-13 17:31:03,019 INFO [network.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_SOCKET: 0
2023-12-13 17:31:03,019 INFO [network.oxalis.commons.settings.SettingsBuilder] Error => TRACKER: quiet
2023-12-13 17:31:03,019 INFO [network.oxalis.commons.settings.SettingsBuilder] AS2 => NOTIFICATION: not.in.use@difi.no
2023-12-13 17:31:03,019 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => CONF:
2023-12-13 17:31:03,020 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: /var/peppol/IN
2023-12-13 17:31:03,020 INFO [network.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: <null>
2023-12-13 17:31:03,020 INFO [network.oxalis.commons.settings.SettingsBuilder] Identifiers => HOSTNAME:
2023-12-13 17:31:03,020 INFO [network.oxalis.commons.settings.SettingsBuilder] Identifiers => MSGID_GENERATOR: default
2023-12-13 17:31:03,020 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => PATH: my_cert.jks
2023-12-13 17:31:03,020 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => PASSWORD: ***
2023-12-13 17:31:03,020 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => KEY_ALIAS: my_cert_alias
2023-12-13 17:31:03,020 INFO [network.oxalis.commons.settings.SettingsBuilder] Key store => KEY_PASSWORD: ***
2023-12-13 17:31:03,020 INFO [network.oxalis.commons.settings.SettingsBuilder] Header => PARSER: sbdh
2023-12-13 17:31:03,021 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => PAYLOAD: default
2023-12-13 17:31:03,021 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => RECEIPT: default
2023-12-13 17:31:03,021 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => EXCEPTION: default
2023-12-13 17:31:03,021 INFO [network.oxalis.commons.settings.SettingsBuilder] Persister => HANDLER: default
2023-12-13 17:31:03,021 INFO [network.oxalis.commons.settings.SettingsBuilder] Tracing => REPORTER: noop
2023-12-13 17:31:03,021 INFO [network.oxalis.commons.settings.SettingsBuilder] Tracing => HTTP: <null>
2023-12-13 17:31:03,021 INFO [network.oxalis.commons.settings.SettingsBuilder] Tracing => TRACER: noop
2023-12-13 17:31:03,021 INFO [network.oxalis.commons.settings.SettingsBuilder] Executor => DEFAULT: 50
2023-12-13 17:31:03,021 INFO [network.oxalis.commons.settings.SettingsBuilder] Executor => STATISTICS: 50
2023-12-13 17:31:03,021 INFO [network.oxalis.commons.settings.SettingsBuilder] Tag => GENERATOR: noop
2023-12-13 17:31:03,022 INFO [network.oxalis.commons.settings.SettingsBuilder] Timestamp => SERVICE: system
2023-12-13 17:31:03,022 INFO [network.oxalis.commons.settings.SettingsBuilder] Evidence => SERVICE: rem
2023-12-13 17:31:03,022 INFO [network.oxalis.commons.settings.SettingsBuilder] Transformer => DETECTOR: noop
2023-12-13 17:31:03,022 INFO [network.oxalis.commons.settings.SettingsBuilder] Transformer => WRAPPER: xml
2023-12-13 17:31:03,022 INFO [network.oxalis.commons.settings.SettingsBuilder] Statistics => SERVICE: noop
2023-12-13 17:31:03,022 INFO [network.oxalis.commons.settings.SettingsBuilder] Transmission => VERIFIER: default
2023-12-13 17:31:03,022 INFO [network.oxalis.commons.settings.SettingsBuilder] AS4 => HOSTNAME:
2023-12-13 17:31:03,022 INFO [network.oxalis.commons.settings.SettingsBuilder] AS4 => MSGID_GENERATOR: default
2023-12-13 17:31:03,022 INFO [network.oxalis.commons.settings.SettingsBuilder] AS4 => TYPE: peppol
2023-12-13 17:31:03,022 INFO [network.oxalis.commons.settings.SettingsBuilder] Logging => CONFIG: logback.xml
2023-12-13 17:31:03,023 INFO [network.oxalis.commons.settings.SettingsBuilder] Logging => SERVICE: logback
2023-12-13 17:31:03,023 INFO [network.oxalis.commons.logging.LoggingHandler] Logging service: logback
Configuring Logback with configuration: /opt/tomcat/.oxalis/logback.xml
17:31:01,599 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 6.3.0
17:31:01,617 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
17:31:01,618 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/var/peppol/OUT/standalone/oxalis-standalone.jar!/logback.xml]
17:31:01,623 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@6f2e1024 - URL [jar:file:/var/peppol/OUT/standalone/oxalis-standalone.jar!/logback.xml] is not of type file
17:31:01,755 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [STDOUT]
17:31:01,755 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
17:31:01,763 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
17:31:01,790 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.apache] to WARN
17:31:01,790 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
17:31:01,790 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[ROOT]
17:31:01,790 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@536d97f8 - End of configuration.
17:31:01,791 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@3c50ad4b - Registering current configuration as safe fallback point
17:31:03,029 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [FILE-ROLLING]
17:31:03,029 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
17:31:04,214 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@927557408 - setting totalSizeCap to 20 GB
17:31:04,215 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@927557408 - Archive files will be limited to [10 MB] each.
17:31:04,217 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@927557408 - Will use gz compression
17:31:04,217 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@927557408 - Will use the pattern /opt/tomcat/logs/archived/oxalis.%d{yyyy-MM-dd}.%i.log for the active file
17:31:04,229 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@28f9fedd - The date pattern is 'yyyy-MM-dd' from file name pattern '/opt/tomcat/logs/archived/oxalis.%d{yyyy-MM-dd}.%i.log.gz'.
17:31:04,229 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@28f9fedd - Roll-over at midnight.
17:31:04,236 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@28f9fedd - Setting initial period to Wed Dec 13 15:24:56 CET 2023
17:31:04,237 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
17:31:04,237 |-ERROR in ch.qos.logback.classic.pattern.LoggerConverter@17947e6d - failed to parse integer string [1.] java.lang.NumberFormatException: For input string: "1."
        at java.lang.NumberFormatException: For input string: "1."
        at      at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at      at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at      at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at      at ch.qos.logback.classic.pattern.NamedConverter.start(NamedConverter.java:92)
        at      at ch.qos.logback.core.pattern.ConverterUtil.startConverters(ConverterUtil.java:37)
        at      at ch.qos.logback.core.pattern.PatternLayoutBase.start(PatternLayoutBase.java:90)
        at      at ch.qos.logback.classic.encoder.PatternLayoutEncoder.start(PatternLayoutEncoder.java:28)
        at      at ch.qos.logback.core.model.processor.ImplicitModelHandler.postHandleComplex(ImplicitModelHandler.java:208)
        at      at ch.qos.logback.core.model.processor.ImplicitModelHandler.postHandle(ImplicitModelHandler.java:186)
        at      at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:257)
        at      at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
        at      at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
        at      at ch.qos.logback.core.model.processor.DefaultProcessor.traversalLoop(DefaultProcessor.java:90)
        at      at ch.qos.logback.core.model.processor.DefaultProcessor.process(DefaultProcessor.java:106)
        at      at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:200)
        at      at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:166)
        at      at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:122)
        at      at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:93)
        at      at network.oxalis.commons.logging.LogbackConfigurator.execute(LogbackConfigurator.java:76)
        at      at network.oxalis.commons.logging.LoggingHandler.load(LoggingHandler.java:51)
        at      at network.oxalis.commons.logging.LoggingHandler$$FastClassByGuice$$80647955.GUICE$TRAMPOLINE(<generated>)
        at      at network.oxalis.commons.logging.LoggingHandler$$FastClassByGuice$$80647955.apply(<generated>)
        at      at com.google.inject.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:50)
        at      at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:87)
        at      at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
        at      at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:101)
        at      at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:245)
        at      at com.google.inject.internal.Initializer.injectAll(Initializer.java:140)
        at      at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at      at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
        at      at com.google.inject.Guice.createInjector(Guice.java:87)
        at      at com.google.inject.Guice.createInjector(Guice.java:69)
        at      at network.oxalis.commons.guice.GuiceModuleLoader.initiate(GuiceModuleLoader.java:66)
        at      at network.oxalis.outbound.OxalisOutboundComponent.<init>(OxalisOutboundComponent.java:45)
        at      at eu.sendregning.oxalis.Main.main(Main.java:117)
17:31:04,238 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE-ROLLING] - Active log file name: /opt/tomcat/logs/oxalis.log
17:31:04,238 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE-ROLLING] - File property is set to [/opt/tomcat/logs/oxalis.log]
17:31:04,238 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.mkyong] to DEBUG
17:31:04,238 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.mkyong] to true
17:31:04,238 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [FILE-ROLLING] to Logger[com.mkyong]
17:31:04,238 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to DEBUG
17:31:04,238 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [FILE-ROLLING] to Logger[ROOT]
17:31:04,238 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@1a0c5e9 - End of configuration.
17:31:04,238 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@123d7057 - Registering current configuration as safe fallback point

Message failed : TransmissionRequest can not be built, missing [c1CountryIdentifier] metadata.

What am I doing wrong?

Thanks.

**Comment by aaron-kumar** [comment]
@DioMeo : First you need to correct logback.xml . 
Secondly this is acceptable behavior. You need to provide "c1CountryIdentifier" as part of SBDH header to send message

**Comment by DioMeo** [comment]
Hello Aaron, I entered that key in my xml files and it worked.
I have a doubt for the statistics, where I need to put the oxalis-statistic.jar? I found it here: https://central.sonatype.com/artifact/network.oxalis/oxalis-statistics/6.3.0/versions but I don't have idea where to put it.
Thanks.

**Comment by aaron-kumar** [comment]
@DioMeo  Refer : https://github.com/OxalisCommunity/oxalis/discussions/655  . Converting it to discussion.
