### ISSUE TITLE
Test certificates in oxalis-test have expired again

### ISSUE THREAD

**Issue by post-svejk** [OxalisCommunity/Oxalis-AS4#237]
I am getting: 
```
$ mvn install
...
WARNING: Interceptor for {http://inbound.as4.oxalis.network/}As4ProviderService has thrown exception, unwinding now
org.apache.cxf.binding.soap.SoapFault: A security error was encountered when verifying the message
	at org.apache.cxf.ws.security.wss4j.WSS4JUtils.createSoapFault(WSS4JUtils.java:240)
...
Caused by: org.apache.wss4j.common.ext.WSSecurityException: The provided certificate is invalid
Original Exception was java.security.cert.CertificateExpiredException: certificate expired on 20240207133846GMT+00:00
	at org.apache.wss4j.common.crypto.Merlin.verifyTrust(Merlin.java:779)
	at org.apache.wss4j.common.crypto.Merlin.verifyTrust(Merlin.java:906)
	at org.apache.wss4j.dom.validate.SignatureTrustValidator.verifyTrustInCerts(SignatureTrustValidator.java:109)
	at org.apache.wss4j.dom.validate.SignatureTrustValidator.validate(SignatureTrustValidator.java:64)
...
[ERROR] Failures: 
[ERROR]   SendReceiveTest.full:101 » OxalisAs4Transmission Failed to send message
[INFO] 
[ERROR] Tests run: 17, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
...
```
when building Oxalis-AS4 from source.
The expiration time matches those from a couple of .cer files in oxalis-test. I suspect they are somehow involved when running integrations tests against a local Oxalis instance. We get the same error in an integration test using an `OxalisOutboundComponent` against a more or less, factory default, local instance of Oxalis (in the same JUnit process).

**Comment by aaron-kumar** [comment]
@post-svejk This is fixed with commit : https://github.com/OxalisCommunity/oxalis/commit/2125e3b7340597b862f5713e54b3af090e0bbbc1 and it is Now part of [Oxalis](https://github.com/OxalisCommunity/oxalis/releases/tag/v6.5.0) & [Oxalis-AS4](https://github.com/OxalisCommunity/Oxalis-AS4/releases/tag/v6.5.0) release.
