### ISSUE TITLE
Error in Testing Oxalis Standalone 

### ISSUE THREAD

**Issue by abmanuel** [OxalisCommunity/Oxalis-AS4#238]
Hi,

I am currently testing oxalis standalone using the latest version 6.4.0. with this command: 

java -classpath "C:/OXALIS_HOME/oxalis-standalone-as4/standalone/*;as4/*" eu.sendregning.oxalis.Main -f  C:\OXALIS_HOME\to-peppol\Invoice-Test03.xml \ -u https://mydomain.com/oxalis/as4 -cert C:\OXALIS_HOME\cert\mycert.p12

And have this error

2024-02-28 07:33:51,801 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] [] Prioritized list of transport profiles: 
2024-02-28 07:33:51,801 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] [] => peppol-transport-as4-v2_0 
2024-02-28 07:33:51,801 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] [] => busdox-transport-as2-ver1p0r1 
2024-02-28 07:33:51,801 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] [] => busdox-transport-as2-ver2p0 
2024-02-28 07:33:51,801 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] [] => busdox-transport-as2-ver1p0 
2024-02-28 07:33:51,810 ERROR [network.oxalis.commons.guice.GuiceModuleLoader] [] Unable to detect mode. 
network.oxalis.api.lang.OxalisLoadingException: Unable to detect mode.
	at network.oxalis.commons.mode.ModeProvider.get(ModeProvider.java:77)
	at network.oxalis.commons.mode.ModeProvider.get(ModeProvider.java:49)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:60)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:59)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at network.oxalis.commons.guice.GuiceModuleLoader.initiate(GuiceModuleLoader.java:66)
	at network.oxalis.outbound.OxalisOutboundComponent.<init>(OxalisOutboundComponent.java:45)
	at eu.sendregning.oxalis.Main.main(Main.java:117)
Caused by: network.oxalis.vefa.peppol.common.lang.PeppolLoadingException: Unable to initiate 'class network.oxalis.vefa.peppol.security.util.DifiCertificateValidator'
	at network.oxalis.vefa.peppol.mode.Mode.initiate(Mode.java:125)
	at network.oxalis.vefa.peppol.mode.Mode.initiate(Mode.java:94)
	at network.oxalis.vefa.peppol.security.ModeDetector.detect(ModeDetector.java:46)
	at network.oxalis.commons.mode.ModeProvider.get(ModeProvider.java:75)
	... 16 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at network.oxalis.vefa.peppol.mode.Mode.initiate(Mode.java:112)
	... 19 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at network.oxalis.commons.certvalidator.ValidatorLoader.build(ValidatorLoader.java:46)
	at network.oxalis.vefa.peppol.security.util.DifiCertificateValidator.<init>(DifiCertificateValidator.java:53)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 22 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:294)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:66)
	at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:57)
	at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:157)
	at com.sun.xml.bind.v2.runtime.reflect.Accessor$FieldReflection.optimize(Accessor.java:255)
	at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.<init>(TransducedAccessor.java:207)
	at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor.get(TransducedAccessor.java:147)
	at com.sun.xml.bind.v2.model.impl.RuntimeClassInfoImpl.calcTransducer(RuntimeClassInfoImpl.java:215)
	at com.sun.xml.bind.v2.model.impl.RuntimeClassInfoImpl.getTransducer(RuntimeClassInfoImpl.java:189)
	at com.sun.xml.bind.v2.model.impl.RuntimeClassInfoImpl.link(RuntimeClassInfoImpl.java:166)
	at com.sun.xml.bind.v2.model.impl.ModelBuilder.link(ModelBuilder.java:424)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.link(RuntimeModelBuilder.java:103)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:448)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:282)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:109)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1142)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:141)
	at com.sun.xml.bind.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:35)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:358)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
	at network.oxalis.commons.certvalidator.ValidatorLoaderParser.<clinit>(ValidatorLoaderParser.java:32)
	... 25 common frames omitted
2024-02-28 07:42:10,624 INFO [network.oxalis.commons.security.CertificateModule] [] Certificate subject: CN=PAU000440, OU=PEPPOL TEST AP, O=Valta Technology Group Pty Ltd, C=AU 
2024-02-28 07:42:10,624 INFO [network.oxalis.commons.security.CertificateModule] [] Certificate issuer: CN=PEPPOL ACCESS POINT TEST CA - G2, OU=FOR TEST ONLY, O=OpenPEPPOL AISBL, C=BE 
2024-02-28 07:42:10,987 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] [] Prioritized list of transport profiles: 
2024-02-28 07:42:10,988 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] [] => busdox-transport-as2-ver1p0r1 
2024-02-28 07:42:10,988 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] [] => busdox-transport-as2-ver2p0 
2024-02-28 07:42:10,988 INFO [network.oxalis.outbound.transmission.MessageSenderFactory] [] => busdox-transport-as2-ver1p0 
2024-02-28 07:42:10,999 ERROR [network.oxalis.commons.guice.GuiceModuleLoader] [] Unable to detect mode. 
network.oxalis.api.lang.OxalisLoadingException: Unable to detect mode.
	at network.oxalis.commons.mode.ModeProvider.get(ModeProvider.java:77)
	at network.oxalis.commons.mode.ModeProvider.get(ModeProvider.java:49)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:60)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:59)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at network.oxalis.commons.guice.GuiceModuleLoader.initiate(GuiceModuleLoader.java:66)
	at network.oxalis.outbound.OxalisOutboundComponent.<init>(OxalisOutboundComponent.java:45)
	at eu.sendregning.oxalis.Main.main(Main.java:117)
Caused by: network.oxalis.vefa.peppol.common.lang.PeppolLoadingException: Unable to initiate 'class network.oxalis.vefa.peppol.security.util.DifiCertificateValidator'
	at network.oxalis.vefa.peppol.mode.Mode.initiate(Mode.java:125)
	at network.oxalis.vefa.peppol.mode.Mode.initiate(Mode.java:94)
	at network.oxalis.vefa.peppol.security.ModeDetector.detect(ModeDetector.java:46)
	at network.oxalis.commons.mode.ModeProvider.get(ModeProvider.java:75)
	... 16 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at network.oxalis.vefa.peppol.mode.Mode.initiate(Mode.java:112)
	... 19 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at network.oxalis.commons.certvalidator.ValidatorLoader.build(ValidatorLoader.java:46)
	at network.oxalis.vefa.peppol.security.util.DifiCertificateValidator.<init>(DifiCertificateValidator.java:53)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 22 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:294)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:66)
	at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:57)
	at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:157)
	at com.sun.xml.bind.v2.runtime.reflect.Accessor$FieldReflection.optimize(Accessor.java:255)
	at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.<init>(TransducedAccessor.java:207)
	at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor.get(TransducedAccessor.java:147)
	at com.sun.xml.bind.v2.model.impl.RuntimeClassInfoImpl.calcTransducer(RuntimeClassInfoImpl.java:215)
	at com.sun.xml.bind.v2.model.impl.RuntimeClassInfoImpl.getTransducer(RuntimeClassInfoImpl.java:189)
	at com.sun.xml.bind.v2.model.impl.RuntimeClassInfoImpl.link(RuntimeClassInfoImpl.java:166)
	at com.sun.xml.bind.v2.model.impl.ModelBuilder.link(ModelBuilder.java:424)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.link(RuntimeModelBuilder.java:103)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:448)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:282)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:109)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1142)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:141)
	at com.sun.xml.bind.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:35)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:358)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
	at network.oxalis.commons.certvalidator.ValidatorLoaderParser.<clinit>(ValidatorLoaderParser.java:32)
	... 25 common frames omitted

Would you help me know what I am doing wrong?

**Comment by aaron-kumar** [comment]
@abmanuel I think you are using private key (p12) instead of required public certificate (cer). 

Moving this is to discussion, since it is Not bug. 
If you are Oxalis member, use Slack channel for quick resolution of these kind of problems.
