### ISSUE TITLE
No transmission is provided

### ISSUE THREAD

**Issue by jonathangraci** [OxalisCommunity/Oxalis-AS4#250]
We have updated the Oxalis version to 6.5.0, but I still have the problem:

Dettaglio errore :  - Identifier '0211:it04513160962' is not registered in SML. - No transmission is provided.

network.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at network.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:116)
        at network.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at com.sbitalia.oxalis.outbound.TransmissionTask.performTransmission(TransmissionTask.java:204)
        at com.sbitalia.oxalis.outbound.TransmissionTask.call(TransmissionTask.java:119)
        at com.sbitalia.oxalis.outbound.TransmissionTask.call(TransmissionTask.java:54)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)
11:35:12,652 |-INFO in ch.qos.logback.classic.net.SMTPAppender[EMAIL-SBI] - About to send out SMTP message "PEPPOL TEST - Errore trasmissione" to [Jonathan.Graci@sbitalia.com, brigida.grassi@sbitalia.com]
2024-05-31_11:35:12.652 ERROR c.s.o.o.u.OxalisEmailNotifyAdminTrace - No transmission is provided.
network.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at network.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:116)
        at network.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at com.sbitalia.oxalis.outbound.TransmissionTask.performTransmission(TransmissionTask.java:204)
        at com.sbitalia.oxalis.outbound.TransmissionTask.call(TransmissionTask.java:119)
        at com.sbitalia.oxalis.outbound.TransmissionTask.call(TransmissionTask.java:54)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)
2024-05-31_11:35:12.726 ERROR com.sbitalia.oxalis.outbound.Main - Execution failed: com.sbitalia.oxalis.outbound.TransmissionException: No transmission is provided.
java.util.concurrent.ExecutionException: com.sbitalia.oxalis.outbound.TransmissionException: No transmission is provided.
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.sbitalia.oxalis.outbound.Main.main(Main.java:262)
Caused by: com.sbitalia.oxalis.outbound.TransmissionException: No transmission is provided.
        at com.sbitalia.oxalis.outbound.TransmissionTask.call(TransmissionTask.java:138)
        at com.sbitalia.oxalis.outbound.TransmissionTask.call(TransmissionTask.java:54)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)

Can you help me?

_Originally posted by @jonathangraci in https://github.com/OxalisCommunity/Oxalis-AS4/issues/245#issuecomment-2141614424_

**Comment by aaron-kumar** [comment]
Provide complete details for debugging: 

- Document type which you are trying to send. Most likely you are trying to send document which is Not registered by receiver in SMP. Share sample document if possible
- Oxalis configuration file (oxalis.conf) without secret/credentials
