### ISSUE TITLE
Reception fails - ResourceResolverException: Could not find a resolver for URI cid:phase4

### ISSUE THREAD

**Issue by Robcio35** [OxalisCommunity/Oxalis-AS4#251]
Hello,
I successfully installed Oxalis AS4 on my Linux server (Ubuntu) with Tomcat 9.
My server is under PEPPOL TESTBED. 
The reception of message fails, with exception : 
**[network.oxalis.as4.inbound.As4FaultInHandler] [] handleFault for Exception
org.apache.cxf.binding.soap.SoapFault: A security error was encountered when verifying the message
...
Caused by: org.apache.xml.security.utils.resolver.ResourceResolverException: Could not find a resolver for URI cid:phase4-att-33cf97b9-0871-4300-b8f9-6055177762cf@cid and Base null
        at org.apache.xml.security.utils.resolver.ResourceResolver.resolve(ResourceResolver.java:161)
        at org.apache.jcp.xml.dsig.internal.dom.DOMURIDereferencer.dereference(DOMURIDereferencer.java:115)
        ... 56 common frames omitted**

Can somebody help me in understanding the origin of this problem ?

Here is my oxalis.conf : 
**oxalis.keystore: {
    path: oxalis-keystore.p12
    password: "xxxx"
    key: {
        alias: "cert"
        password: "xxxx"
    }
}
oxalis.truststore.ap: {
    path: oxalis-truststore.jks
    password: "yyyy"
}
oxalis.path.inbound = /var/peppol/IN
oxalis.logging.config=logback.xml**

I will really appreciate any advice or help.

R.

**Comment by Robcio35** [comment]
Additional information : 
My AS4 succeeds in testbed of messages submission.
Only reception of message fails.
Any idea what's wrong in my configuration ?

**Comment by Robcio35** [comment]
I finally found the origin of this issue : on the same server was installed another AP software "Domibus" which was disturbing the reception of messages by AS4. I just uninstalled Domibus, and Oxalis works correctly now in reception and sending.
