### ISSUE TITLE
Unable to verify document signature

### ISSUE THREAD

**Issue by jonathangraci** [OxalisCommunity/Oxalis-AS4#252]
When I try to send an order with Oxalis (version 6.5.0) I get the following error:

Message failed : Unable to verify document signature.
 
Message failed : Unable to verify document signature.
 
09:19:31,633 |-INFO in ch.qos.logback.classic.net.SMTPAppender[EMAIL-SBI] - About to send out SMTP message "PEPPOL - Errore trasmissione" to [[Jonathan.Graci@sbitalia.com](mailto:Jonathan.Graci@sbitalia.com), [brigida.grassi@sbitalia.com](mailto:brigida.grassi@sbitalia.com)]
09:19:31,777 |-INFO in ch.qos.logback.classic.net.SMTPAppender[EMAIL-SBI] - SMTPAppender [EMAIL-SBI] is tracking [1] buffers
2024-07-08_09:19:31.426 ERROR c.s.o.o.u.OxalisEmailNotifyAdminTrace - No transmission is provided.
network.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at network.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:116)
        at network.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at com.sbitalia.oxalis.outbound.TransmissionTask.performTransmission(TransmissionTask.java:204)
        at com.sbitalia.oxalis.outbound.TransmissionTask.call(TransmissionTask.java:119)
        at com.sbitalia.oxalis.outbound.TransmissionTask.call(TransmissionTask.java:54)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)
09:19:31,779 |-INFO in ch.qos.logback.classic.net.SMTPAppender[EMAIL-SBI] - About to send out SMTP message "PEPPOL - Errore trasmissione" to [[Jonathan.Graci@sbitalia.com](mailto:Jonathan.Graci@sbitalia.com), [brigida.grassi@sbitalia.com](mailto:brigida.grassi@sbitalia.com)]
2024-07-08_09:19:31.428 ERROR c.s.o.o.u.OxalisEmailNotifyAdminTrace - No transmission is provided.
network.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at network.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:116)
        at network.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at com.sbitalia.oxalis.outbound.TransmissionTask.performTransmission(TransmissionTask.java:204)
        at com.sbitalia.oxalis.outbound.TransmissionTask.call(TransmissionTask.java:119)
        at com.sbitalia.oxalis.outbound.TransmissionTask.call(TransmissionTask.java:54)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)
2024-07-08_09:19:31.781 ERROR com.sbitalia.oxalis.outbound.Main - Execution failed: com.sbitalia.oxalis.outbound.TransmissionException: No transmission is provided.
java.util.concurrent.ExecutionException: com.sbitalia.oxalis.outbound.TransmissionException: No transmission is provided.
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.sbitalia.oxalis.outbound.Main.main(Main.java:262)
Caused by: com.sbitalia.oxalis.outbound.TransmissionException: No transmission is provided.
        at com.sbitalia.oxalis.outbound.TransmissionTask.call(TransmissionTask.java:138)
        at com.sbitalia.oxalis.outbound.TransmissionTask.call(TransmissionTask.java:54)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)
2024-07-08_09:19:31.875 ERROR com.sbitalia.oxalis.outbound.Main - Execution failed: com.sbitalia.oxalis.outbound.TransmissionException: No transmission is provided.
java.util.concurrent.ExecutionException: com.sbitalia.oxalis.outbound.TransmissionException: No transmission is provided.
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.sbitalia.oxalis.outbound.Main.main(Main.java:262)
Caused by: com.sbitalia.oxalis.outbound.TransmissionException: No transmission is provided.
        at com.sbitalia.oxalis.outbound.TransmissionTask.call(TransmissionTask.java:138)
        at com.sbitalia.oxalis.outbound.TransmissionTask.call(TransmissionTask.java:54)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)

Can you help me understand?

Thank you,
Jonathan.

**Comment by aaron-kumar** [comment]
It seems that you are Not providing necessary parameters or there is some misconfiguration/additional conflicting stuff. 
Is it possible for you to share complete logs and Oxalis configuration file (_without internal details_)?

**Comment by jonathangraci** [comment]
I share the configuration file (oxalis.conf) and the logs. Let me know if you need anything else.

[oxalis.txt](https://github.com/user-attachments/files/16231116/oxalis.txt)
[catalina.2024-07-15.zip](https://github.com/user-attachments/files/16231120/catalina.2024-07-15.zip)

Thank you,
Jonathan.

**Comment by aaron-kumar** [comment]
You mentioned, when you tried to sending Order. What about receiving? Is receiving working fine? 

Did you tried sending through Oxalis standalone? If yes, then can you share command that you are using? If Not, then try sending once with Oxalis standalone especially in isolated environment (_without any conflicting libraries etc_). 

Always try to dig out issue which may be specific to your environment. You know your system/environment best so you have to find out reason OR provide all details (_e.g. everything Oxalis version, Java version, additional libraries that you may be using that can create conflict, so on ..._) 

Based on analysis so far, this is Not an Oxalis issue but an environment issue. So please work on that direction. I will be converting this to github discussion. If you are Not Oxalis Gold member, join Oxalis Membership to get help from community of Oxalis Users through Slack channel.

**Comment by jonathangraci** [comment]
On the receiving side I have no problem. I receive orders daily.

The command I use to send is the following:

java -Dlogback.configurationFile=C:\Oxalis\OXALIS_OUTGOING\logback.xml -classpath "C:\Oxalis\OXALIS_OUTGOING\standalone\*;C:\Oxalis\OXALIS_OUTGOING\as4\*" com.sbitalia.oxalis.outbound.Main -protocol peppol-transport-as4-v2_0

I also attach a EUSR report that I'm trying to send but I always get error. I also get the same error with orders.

[eusr.txt](https://github.com/user-attachments/files/16244761/eusr.txt)

Thank you,
Jonathan.

**Comment by aaron-kumar** [comment]
Please see my above response. This is Not an Oxalis bug but configuration issue at your side. 

For discussion sake, can you share complete standalone logs? 
You can use following standalone command (_no need to define additional parameters_):
`java -cp "D:\oxalis-distribution-6.6.0-distro\bin\*;D:\oxalis-as4-6.6.0-dist\*" eu.sendregning.oxalis.Main -f "D:\eusr.xml" `

You can define logback setting in "oxalis.conf" through property: 
`oxalis.logging.config = logback-oxalis-outbound.xml`
