### ISSUE TITLE
Failed to send message - com.ctc.wstx.exc.WstxIOException

### ISSUE THREAD

**Issue by senikk** [OxalisCommunity/Oxalis-AS4#98]
Some of the "Failed to send message" seems to be because of com.ctc.wstx.exc.WstxIOException / java.net.UnknownHostException. The real address is replaced with xx.yy.com, its several addresses not just one accesspoint.

`org.apache.cxf.binding.soap.SoapFault: Problem writing SAAJ model to stream: xx.yy.com
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:224)
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:174)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
	at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
	at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)
	at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
	at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:95)
	at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:87)
	at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
	at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:106)
	at no.unimicro.ap.outbox.UniSendService.sendFileToReceiver(UniSendService.java:175)
	at no.unimicro.ap.outbox.UniSendService.main(UniSendService.java:111)
Caused by: com.ctc.wstx.exc.WstxIOException: xx.yy.com
	at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:471)
	at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:770)
	at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:716)
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:214)
	... 17 common frames omitted
Caused by: java.net.UnknownHostException: xx.yy.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.setupWrappedStream(URLConnectionHTTPConduit.java:274)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleHeadersTrustCaching(HTTPConduit.java:1343)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.onFirstWrite(HTTPConduit.java:1304)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.onFirstWrite(URLConnectionHTTPConduit.java:307)
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:47)
	at org.apache.cxf.io.AbstractThresholdOutputStream.unBuffer(AbstractThresholdOutputStream.java:89)
	at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:63)
	at org.apache.cxf.io.CacheAndWriteOutputStream.write(CacheAndWriteOutputStream.java:80)
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:51)
	at com.ctc.wstx.io.UTF8Writer.write(UTF8Writer.java:143)
	at com.ctc.wstx.sw.BufferingXmlWriter.writeRaw(BufferingXmlWriter.java:286)
	at com.ctc.wstx.sw.BufferingXmlWriter.writeCharacters(BufferingXmlWriter.java:600)
	at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:469)
	... 20 common frames omitted
EXCEPTION: Failed to send message`

**Comment by FrodeBjerkholt** [comment]
So there are several hosts that fails on DNS lookup?

**Comment by senikk** [comment]
Atleast two. I'm downloading all logs now from the last days to see if there are more of these kind of errors.

**Comment by SuperJuell** [comment]
Is this still a problem? If so, we will look into it.

**Comment by aaron-kumar** [comment]
Issue is inactive and nobody reported issue 18 months, so closing issue. 

Please feel free to reopen if you are still facing this issue.
